# Generated by Django 3.2.5 on 2021-07-06 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=3)),
                ('start_date', models.DateTimeField(verbose_name='date added')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.emergencycontact')),
            ],
        ),
    ]
