-- AlterTable
ALTER TABLE "Setting" ADD COLUMN     "controls" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "playbackRate" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN     "volume" DOUBLE PRECISION NOT NULL DEFAULT 0.5;
